server:
  port: 9003 #端口号

spring:
  application:
    name: nacos-sentinel-payment-provider #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露所有端口