server:
  port: 83 #端口号

spring:
  application:
    name: nacos-order-consumer #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos地址

service-url:
  nacos-payment-service: http://nacos-payment-provider